export type CompatibilityStatus = "Ready to connect" | "Cable needed" | "Check details";

export type Listing = {
    id: string;
    brand: string;
    model: string;
    generation: string;
    category: "Audio interfaces" | "Microphones" | "Monitors" | "Headphones" | "MIDI controllers" | "Accessories";
    condition: "Excellent" | "Very good" | "Good" | "Open box";
    price: number;
    location: string;
    seller: string;
    sellerInitials: string;
    sellerRating: number;
    title: string;
    description: string;
    image: string;
    imagePosition?: string;
    tags: string[];
    ports: string[];
    included: string[];
    missing: string[];
    compatibility: CompatibilityStatus;
    compatibilitySummary: string;
    facts: string[];
    evidence: string;
    published: string;
};

export const categories = [
    "All gear",
    "Audio interfaces",
    "Microphones",
    "Monitors",
    "Headphones",
    "MIDI controllers",
    "Accessories",
] as const;

export const listings: Listing[] = [
    {
        id: "focusrite-scarlett-2i2-4th-gen",
        brand: "Focusrite",
        model: "Scarlett 2i2",
        generation: "4th Gen",
        category: "Audio interfaces",
        condition: "Excellent",
        price: 245,
        location: "Tiong Bahru",
        seller: "Mika Tan",
        sellerInitials: "MT",
        sellerRating: 4.9,
        title: "Focusrite Scarlett 2i2 4th Gen",
        description: "Two-input USB-C interface in excellent working condition. Used lightly at a home desk and includes the original USB-C cable.",
        image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=85",
        imagePosition: "center",
        tags: ["USB-C", "2 inputs", "48V phantom power", "Mac / Windows"],
        ports: ["2 × XLR / ¼ in combo inputs", "2 × ¼ in balanced outputs", "¼ in headphone output", "USB-C"],
        included: ["USB-C to USB-C cable", "Original box"],
        missing: ["XLR microphone cable"],
        compatibility: "Ready to connect",
        compatibilitySummary: "A strong match for a USB-C MacBook, an XLR vocal microphone, headphones, and powered studio monitors.",
        facts: ["Two microphone preamps", "48V phantom power is available", "USB-C host connection", "Balanced monitor outputs"],
        evidence: "Manufacturer product documentation · Scarlett 2i2 4th Gen",
        published: "Today",
    },
    {
        id: "rode-nt1-signature",
        brand: "RØDE",
        model: "NT1 Signature Series",
        generation: "5th Gen capsule",
        category: "Microphones",
        condition: "Open box",
        price: 185,
        location: "Bishan",
        seller: "Cheryl Lim",
        sellerInitials: "CL",
        sellerRating: 5,
        title: "RØDE NT1 Signature Series",
        description: "Barely used large-diaphragm condenser microphone. Bought for a project and stored in its original box afterwards.",
        image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=85",
        tags: ["Condenser", "XLR", "Vocals", "48V required"],
        ports: ["3-pin XLR output"],
        included: ["Shock mount", "Pop filter", "XLR cable"],
        missing: ["Audio interface with 48V phantom power"],
        compatibility: "Cable needed",
        compatibilitySummary: "Works with an XLR interface that can supply 48V phantom power. A compatible XLR cable is included.",
        facts: ["Condenser microphone", "Requires 48V phantom power", "XLR connection"],
        evidence: "Manufacturer product documentation · NT1 Signature Series",
        published: "1 day ago",
    },
    {
        id: "yamaha-hs5-pair",
        brand: "Yamaha",
        model: "HS5",
        generation: "Pair",
        category: "Monitors",
        condition: "Very good",
        price: 320,
        location: "Queenstown",
        seller: "Darren Khoo",
        sellerInitials: "DK",
        sellerRating: 4.8,
        title: "Yamaha HS5 powered monitors — pair",
        description: "Matched pair, kept in a smoke-free project studio. Both speakers tested; minor cosmetic mark on one rear corner.",
        image: "https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?auto=format&fit=crop&w=1200&q=85",
        tags: ["Powered", "5-inch", "XLR / TRS", "Pair"],
        ports: ["XLR balanced input", "¼ in TRS balanced input", "IEC power input"],
        included: ["2 × IEC power cables"],
        missing: ["Pair of balanced monitor cables"],
        compatibility: "Cable needed",
        compatibilitySummary: "Connect to an audio interface’s balanced line outputs using two XLR or TRS monitor cables.",
        facts: ["Active / powered speakers", "One balanced input per speaker", "No speaker amplifier required"],
        evidence: "Manufacturer owner’s manual · HS5",
        published: "2 days ago",
    },
    {
        id: "audio-technica-ath-m50x",
        brand: "Audio-Technica",
        model: "ATH-M50x",
        generation: "Black",
        category: "Headphones",
        condition: "Excellent",
        price: 118,
        location: "Kallang",
        seller: "Jia Wen",
        sellerInitials: "JW",
        sellerRating: 4.9,
        title: "Audio-Technica ATH-M50x",
        description: "Closed-back monitoring headphones with clean pads and all three detachable cables. Great for late-night tracking.",
        image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=85",
        tags: ["Closed-back", "Monitoring", "¼ in adapter", "Detachable cable"],
        ports: ["3.5 mm locking headphone connection", "3.5 mm plug with ¼ in adapter"],
        included: ["Straight cable", "Coiled cable", "Short cable", "¼ in adapter", "Pouch"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Connects directly to common 3.5 mm or ¼ in headphone outputs, including the Scarlett 2i2.",
        facts: ["Closed-back design", "Includes ¼ in screw-on adapter", "Detachable cables"],
        evidence: "Manufacturer product documentation · ATH-M50x",
        published: "3 days ago",
    },
    {
        id: "arturia-minilab-3",
        brand: "Arturia",
        model: "MiniLab 3",
        generation: "White",
        category: "MIDI controllers",
        condition: "Excellent",
        price: 105,
        location: "Toa Payoh",
        seller: "Nadia F",
        sellerInitials: "NF",
        sellerRating: 4.7,
        title: "Arturia MiniLab 3 MIDI controller",
        description: "Compact 25-key USB MIDI controller. All pads, keys, knobs and USB connection tested before listing.",
        image: "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=1200&q=85",
        tags: ["USB-C", "25 keys", "MIDI", "Mac / Windows"],
        ports: ["USB-C", "MIDI out (TRS Type B)"],
        included: ["USB-C cable", "Original box"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Connects over USB-C to a MacBook or Windows computer for MIDI control; it does not produce audio by itself.",
        facts: ["Bus-powered over USB-C", "MIDI controller, not an audio interface", "TRS Type B MIDI output"],
        evidence: "Manufacturer product documentation · MiniLab 3",
        published: "4 days ago",
    },
    {
        id: "shure-sm58",
        brand: "Shure",
        model: "SM58",
        generation: "Cardioid dynamic",
        category: "Microphones",
        condition: "Good",
        price: 82,
        location: "Bedok",
        seller: "Irfan Rahim",
        sellerInitials: "IR",
        sellerRating: 4.8,
        title: "Shure SM58 dynamic vocal microphone",
        description: "Original SM58 with a few honest stage marks. Capsule sounds clear; grille and XLR connection tested.",
        image: "https://images.unsplash.com/photo-1524368535928-5b5e00ddc76b?auto=format&fit=crop&w=1200&q=85",
        tags: ["Dynamic", "XLR", "Vocals", "No phantom power"],
        ports: ["3-pin XLR output"],
        included: ["Mic clip", "Zip pouch"],
        missing: ["XLR microphone cable", "Mic stand"],
        compatibility: "Cable needed",
        compatibilitySummary: "Works with an XLR microphone input. It does not require phantom power; add an XLR cable and stand for a full setup.",
        facts: ["Dynamic microphone", "XLR connection", "Does not require phantom power"],
        evidence: "Manufacturer user guide · SM58",
        published: "4 days ago",
    },
    {
        id: "presonus-eris-3-5",
        brand: "PreSonus",
        model: "Eris 3.5",
        generation: "2nd Gen pair",
        category: "Monitors",
        condition: "Very good",
        price: 145,
        location: "Hougang",
        seller: "Grace Yap",
        sellerInitials: "GY",
        sellerRating: 5,
        title: "PreSonus Eris 3.5 studio monitors",
        description: "Compact powered desktop monitors. Great condition, ideal for a smaller room or first home studio.",
        image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=85",
        tags: ["Powered", "Desktop", "TRS / RCA", "Pair"],
        ports: ["¼ in TRS balanced inputs", "RCA inputs", "3.5 mm aux input", "Headphone output"],
        included: ["Speaker link cable", "Power cable"],
        missing: ["Balanced monitor cables, if using an interface"],
        compatibility: "Cable needed",
        compatibilitySummary: "Use a pair of ¼ in TRS monitor cables from an audio interface for a balanced connection.",
        facts: ["Active / powered pair", "Front headphone output", "Balanced TRS inputs available"],
        evidence: "Manufacturer owner’s manual · Eris 3.5",
        published: "5 days ago",
    },
    {
        id: "behringer-umc202hd",
        brand: "Behringer",
        model: "U-Phoria UMC202HD",
        generation: "USB-B",
        category: "Audio interfaces",
        condition: "Good",
        price: 78,
        location: "Clementi",
        seller: "Sean Goh",
        sellerInitials: "SG",
        sellerRating: 4.6,
        title: "Behringer U-Phoria UMC202HD",
        description: "Budget two-input interface. Inputs, phantom power, headphone output and monitor outputs tested before listing.",
        image: "https://images.unsplash.com/photo-1487180144351-b8472da7d491?auto=format&fit=crop&w=1200&q=85",
        tags: ["USB-B", "2 inputs", "48V phantom power", "Budget"],
        ports: ["2 × XLR / ¼ in combo inputs", "2 × ¼ in outputs", "¼ in headphone output", "USB-B"],
        included: ["USB-A to USB-B cable"],
        missing: ["USB-C adapter or USB-C to USB-B cable for USB-C MacBooks"],
        compatibility: "Check details",
        compatibilitySummary: "Supports XLR microphones and 48V phantom power. USB-C laptops need an adapter or compatible USB-C to USB-B cable.",
        facts: ["Two combo input channels", "48V phantom power", "USB-B host connection"],
        evidence: "Manufacturer quick start guide · UMC202HD",
        published: "6 days ago",
    },
    {
        id: "akai-mpk-mini-plus",
        brand: "Akai",
        model: "MPK Mini Plus",
        generation: "37-key",
        category: "MIDI controllers",
        condition: "Excellent",
        price: 155,
        location: "Serangoon",
        seller: "Marc Lee",
        sellerInitials: "ML",
        sellerRating: 4.9,
        title: "Akai MPK Mini Plus MIDI keyboard",
        description: "37-key controller with sequencer. Includes USB cable and original box; all controls working smoothly.",
        image: "https://images.unsplash.com/photo-1552422535-c45813c61732?auto=format&fit=crop&w=1200&q=85",
        tags: ["USB", "37 keys", "MIDI I/O", "Sequencer"],
        ports: ["USB", "5-pin MIDI in", "5-pin MIDI out", "CV / Gate"],
        included: ["USB cable", "Original box"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Use USB for computer-based MIDI production. Its MIDI ports can also communicate with compatible external hardware.",
        facts: ["USB MIDI controller", "No onboard audio interface", "5-pin MIDI I/O"],
        evidence: "Manufacturer product documentation · MPK Mini Plus",
        published: "1 week ago",
    },
    {
        id: "mogami-xlr-3m",
        brand: "Mogami",
        model: "Gold Studio XLR",
        generation: "3 m",
        category: "Accessories",
        condition: "Excellent",
        price: 36,
        location: "Novena",
        seller: "Jules N",
        sellerInitials: "JN",
        sellerRating: 4.9,
        title: "Mogami Gold Studio XLR cable — 3 m",
        description: "One 3 m XLR female-to-male microphone cable. Clean connectors and strain relief; continuity tested.",
        image: "https://images.unsplash.com/photo-1558098329-a11cff621064?auto=format&fit=crop&w=1200&q=85",
        tags: ["XLR", "3 m", "Mic cable", "Tested"],
        ports: ["XLR female to XLR male"],
        included: ["One XLR cable"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Connects an XLR microphone such as the NT1 or SM58 to an XLR input on a compatible audio interface.",
        facts: ["Female XLR microphone end", "Male XLR interface end", "3 m length"],
        evidence: "Seller test statement · connector type verified",
        published: "1 week ago",
    },
    {
        id: "sennheiser-hd-280-pro",
        brand: "Sennheiser",
        model: "HD 280 PRO",
        generation: "New edition",
        category: "Headphones",
        condition: "Very good",
        price: 88,
        location: "Ang Mo Kio",
        seller: "Ashvin R",
        sellerInitials: "AR",
        sellerRating: 4.7,
        title: "Sennheiser HD 280 PRO",
        description: "Comfortable closed-back studio headphones. Pads replaced recently; coiled cable and ¼ inch adapter included.",
        image: "https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=1200&q=85",
        tags: ["Closed-back", "Monitoring", "¼ in adapter", "Coiled cable"],
        ports: ["3.5 mm plug with ¼ in adapter"],
        included: ["¼ in adapter", "Coiled cable"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Works with standard headphone outputs; the included adapter fits common ¼ in audio-interface headphone jacks.",
        facts: ["Closed-back monitoring headphones", "¼ in adapter included"],
        evidence: "Manufacturer product documentation · HD 280 PRO",
        published: "1 week ago",
    },
    {
        id: "k-mic-stand-pop-filter",
        brand: "K&M",
        model: "210/9 Boom Stand + pop filter",
        generation: "Bundle",
        category: "Accessories",
        condition: "Good",
        price: 45,
        location: "Bukit Merah",
        seller: "Hana Soh",
        sellerInitials: "HS",
        sellerRating: 4.8,
        title: "K&M boom mic stand + pop filter",
        description: "Stable boom stand with an adjustable pop filter. Some minor paint wear but all clamps hold securely.",
        image: "https://images.unsplash.com/photo-1517230878791-4d28214057c2?auto=format&fit=crop&w=1200&q=85",
        tags: ["Mic stand", "Pop filter", "Vocal recording", "Bundle"],
        ports: ["Standard microphone clip thread"],
        included: ["Boom stand", "Pop filter", "Mic clip"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Provides physical support and plosive control for standard vocal microphones with a compatible mic clip.",
        facts: ["Boom stand", "Pop filter included", "Standard mic clip thread"],
        evidence: "Seller statement · bundle contents",
        published: "2 weeks ago",
    },
    {
        id: "audient-evo-4",
        brand: "Audient",
        model: "EVO 4",
        generation: "USB-C",
        category: "Audio interfaces",
        condition: "Very good",
        price: 135,
        location: "Toa Payoh",
        seller: "Priya Nair",
        sellerInitials: "PN",
        sellerRating: 4.8,
        title: "Audient EVO 4 USB-C interface",
        description: "Compact two-input USB-C interface with smart gain. Tested inputs, phantom power, and headphone output before listing.",
        image: "https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=85",
        tags: ["USB-C", "2 inputs", "48V phantom power", "Smart gain"],
        ports: ["2 × XLR / ¼ in combo inputs", "2 × ¼ in balanced outputs", "¼ in headphone output", "USB-C"],
        included: ["USB-C to USB-C cable", "Quick start guide"],
        missing: ["XLR microphone cable"],
        compatibility: "Ready to connect",
        compatibilitySummary: "A strong match for a USB-C computer, an XLR vocal microphone, headphones, and powered studio monitors.",
        facts: ["Two microphone preamps", "48V phantom power is available", "USB-C host connection", "Balanced monitor outputs"],
        evidence: "Manufacturer product documentation · EVO 4",
        published: "2 weeks ago",
    },
    {
        id: "audio-technica-at2020",
        brand: "Audio-Technica",
        model: "AT2020",
        generation: "XLR",
        category: "Microphones",
        condition: "Very good",
        price: 98,
        location: "Jurong East",
        seller: "Daniel Ong",
        sellerInitials: "DO",
        sellerRating: 4.7,
        title: "Audio-Technica AT2020 condenser microphone",
        description: "Cardioid condenser for vocals and acoustic instruments. Clean capsule, tested XLR output, includes pouch.",
        image: "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?auto=format&fit=crop&w=1200&q=85",
        tags: ["Condenser", "XLR", "Vocals", "48V required"],
        ports: ["3-pin XLR output"],
        included: ["Pouch", "Mic clip"],
        missing: ["Audio interface with 48V phantom power", "XLR microphone cable"],
        compatibility: "Cable needed",
        compatibilitySummary: "Works with an XLR interface that can supply 48V phantom power. Add an XLR cable for a full setup.",
        facts: ["Condenser microphone", "Requires 48V phantom power", "XLR connection"],
        evidence: "Manufacturer product documentation · AT2020",
        published: "2 weeks ago",
    },
    {
        id: "krk-rokit-5-g5",
        brand: "KRK",
        model: "Rokit 5",
        generation: "G5 pair",
        category: "Monitors",
        condition: "Good",
        price: 265,
        location: "Woodlands",
        seller: "Farah Begum",
        sellerInitials: "FB",
        sellerRating: 4.6,
        title: "KRK Rokit 5 G5 monitors — pair",
        description: "Pair of powered nearfield monitors with room-tuning EQ. Both drivers tested; light scuffs on cabinets.",
        image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=1200&q=85",
        tags: ["Powered", "5-inch", "XLR / TRS", "Pair"],
        ports: ["XLR balanced input", "¼ in TRS balanced input", "IEC power input"],
        included: ["2 × IEC power cables"],
        missing: ["Pair of balanced monitor cables"],
        compatibility: "Cable needed",
        compatibilitySummary: "Connect to an audio interface's balanced line outputs using two XLR or TRS monitor cables.",
        facts: ["Active / powered speakers", "One balanced input per speaker", "No speaker amplifier required"],
        evidence: "Manufacturer owner's manual · Rokit 5 G5",
        published: "2 weeks ago",
    },
    {
        id: "beyerdynamic-dt-770-80",
        brand: "Beyerdynamic",
        model: "DT 770 PRO 80",
        generation: "80 ohm",
        category: "Headphones",
        condition: "Very good",
        price: 145,
        location: "Pasir Ris",
        seller: "Kevin Chua",
        sellerInitials: "KC",
        sellerRating: 4.9,
        title: "Beyerdynamic DT 770 PRO 80 ohm",
        description: "Closed-back tracking headphones with fresh pads. Coiled cable and ¼ inch adapter included and tested.",
        image: "https://images.unsplash.com/photo-1583394838336-acd977736f90?auto=format&fit=crop&w=1200&q=85",
        tags: ["Closed-back", "Monitoring", "¼ in adapter", "Coiled cable"],
        ports: ["3.5 mm plug with ¼ in adapter"],
        included: ["¼ in adapter", "Coiled cable"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Works with standard headphone outputs; the included adapter fits common ¼ in audio-interface headphone jacks.",
        facts: ["Closed-back monitoring headphones", "¼ in adapter included", "80 ohm impedance"],
        evidence: "Manufacturer product documentation · DT 770 PRO",
        published: "3 weeks ago",
    },
    {
        id: "novation-launchkey-mini-37",
        brand: "Novation",
        model: "Launchkey Mini 37",
        generation: "MK4",
        category: "MIDI controllers",
        condition: "Excellent",
        price: 165,
        location: "Sengkang",
        seller: "Alicia Pang",
        sellerInitials: "AP",
        sellerRating: 5,
        title: "Novation Launchkey Mini 37-key controller",
        description: "37-key USB-C MIDI controller with pads and arpeggiator. All keys and pads tested; includes cable and box.",
        image: "https://images.unsplash.com/photo-1552422535-c45813c61732?auto=format&fit=crop&w=1200&q=85",
        tags: ["USB-C", "37 keys", "MIDI", "Mac / Windows"],
        ports: ["USB-C", "MIDI out (TRS Type A)"],
        included: ["USB-C cable", "Original box"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Connects over USB-C to a computer for MIDI control; it does not produce audio by itself.",
        facts: ["Bus-powered over USB-C", "MIDI controller, not an audio interface", "TRS Type A MIDI output"],
        evidence: "Manufacturer product documentation · Launchkey Mini 37",
        published: "3 weeks ago",
    },
    {
        id: "hosa-trs-pair-2m",
        brand: "Hosa",
        model: "TRS monitor cable pair",
        generation: "2 m",
        category: "Accessories",
        condition: "Excellent",
        price: 28,
        location: "Tampines",
        seller: "Ravi Menon",
        sellerInitials: "RM",
        sellerRating: 4.8,
        title: "Balanced TRS monitor cable pair — 2 m",
        description: "Matched pair of 2 m balanced ¼ inch TRS cables for monitors. Continuity tested on both cables.",
        image: "https://images.unsplash.com/photo-1558098329-a11cff621064?auto=format&fit=crop&w=1200&q=85",
        tags: ["TRS", "Balanced", "Monitor cables", "Pair"],
        ports: ["¼ in TRS male to ¼ in TRS male, pair"],
        included: ["Two TRS cables"],
        missing: [],
        compatibility: "Ready to connect",
        compatibilitySummary: "Connects balanced interface line outputs to the balanced inputs of powered studio monitors.",
        facts: ["Balanced TRS plugs both ends", "2 m length per cable", "Stereo pair"],
        evidence: "Seller test statement · continuity verified",
        published: "3 weeks ago",
    },
];

export const findListing = (id: string) => listings.find((listing) => listing.id === id);

export const catalogueContext = (items: Listing[] = listings) =>
    items
        .map(
            (item) =>
                `${item.id}: ${item.title}; category=${item.category}; S$${item.price}; condition=${item.condition}; tags=${item.tags.join(", ")}; ports=${item.ports.join(", ")}; included=${item.included.join(", ")}; missing=${item.missing.join(", ") || "none"}; facts=${item.facts.join(", ")}; compatibility=${item.compatibility}.`,
        )
        .join("\n");