import Link from "next/link";
import { SparkleIcon } from "@/components/Icons";

export default function NotesPage() {
    return (
        <main>
            <header className="site-header compact-header"><Link href="/" className="wordmark" aria-label="RigGraph home"><span>R</span>RIGGRAPH</Link><nav className="desktop-nav"><Link href="/">Browse gear</Link><Link href="/notes">Notes</Link></nav><Link className="back-link" href="/">← Back to browse</Link></header>
            <article className="notes-page">
                <p className="eyebrow"><span className="eyebrow-dot" /> CognitioLabs candidate assessment</p>
                <h1>Notes on the demo.</h1>
                <p className="notes-intro">RigGraph is a responsive, AI-enabled second-hand marketplace demo for Singapore musicians building a first home-recording setup. Its point of view is simple: used music gear is easier to buy when the connection details are visible before the seller chat begins.</p>
                <div className="notes-grid">
                    <section className="note-block"><h2>1. What I built and who it is for</h2><p>A public, mobile-first marketplace where a beginner or intermediate musician can browse structured used listings, inspect an item detail page, search in natural language, and ask questions about a catalogue record. The demo focuses on home-recording essentials: audio interfaces, microphones, monitors, headphones, MIDI controllers, and a handful of required accessories.</p></section>
                    <section className="note-block"><h2>2. What is seeded, simulated, or limited</h2><ul><li>The catalogue contains 12 illustrative listings and fabricated seller identities, condition, price, and Singapore pickup locations.</li><li>Listing photos are illustrative Unsplash images rather than photos supplied by real sellers.</li><li>Save, request-to-buy, payment, delivery, accounts, messaging, and pickup are intentionally simulated or unavailable.</li><li>Compatibility states are concise, seeded notes—not a complete rules engine or safety certification.</li><li>The demo cannot verify real-time availability, condition, authenticity, driver compatibility, electrical safety, or undocumented accessories.</li></ul></section>
                    <section className="note-block"><h2>3. AI implementation</h2><p>I built the experience with an AI coding assistant. The demo includes two server-side AI integration points: natural-language listing search and listing/catalogue Q&amp;A. When configured, they call an OpenAI-compatible CognitioLabs gateway using <code>AI_GATEWAY_API_KEY</code>, <code>AI_GATEWAY_BASE_URL</code>, and <code>AI_MODEL</code> environment variables only. No browser-side API key is required or exposed.</p><ul><li>Search receives the seeded catalogue and is constrained to return only existing listing IDs plus a concise rationale.</li><li>Q&amp;A receives only the active listing (and an optional comparison listing) and must return known facts separately from unknowns.</li><li>Server responses validate model-selected IDs before rendering. If the gateway is missing or fails, deterministic seeded-catalogue fallbacks keep the public demo usable.</li></ul></section>
                    <section className="note-block"><h2>4. What I chose not to build, and why</h2><p>I prioritised one credible buyer journey—browse → item detail → grounded search or Q&amp;A—over full marketplace infrastructure. Authentication, seller onboarding, photo ingestion, moderation, payments, logistics, persistent saved gear, and a broad visual-rig/compatibility engine would dilute the quality of the assessed experience in this time-boxed demo. The PRD&apos;s long-term vision would need those systems, but they are not required to demonstrate the catalogue and AI interaction hypothesis.</p></section>
                    <section className="note-block"><h2>5. Known issues and unfinished parts</h2><ul><li>Real model responses require the candidate gateway variables to be set on the deployed service. Without them, the same UI works using transparent deterministic catalogue fallbacks.</li><li>Catalogue facts were manually seeded and are representative, not a complete or independently audited product database.</li><li>Natural-language matching is limited by the small demo catalogue and does not yet synthesise a multi-item rig or enforce every physical signal-path rule.</li><li>Images load from Unsplash and therefore depend on external image availability.</li><li>There are no automated tests yet; the intended manual checks are public/incognito browse, mobile layout, search, Q&amp;A, and this notes page.</li></ul></section>
                </div>
                <aside className="notes-callout"><SparkleIcon /><p><strong>Safety and transparency note.</strong> Model-backed output is treated as a catalogue explanation, not expert technical advice. The UI labels uncertainty and source limitations rather than claiming that an item is safe, authentic, or guaranteed compatible.</p></aside>
                <footer className="notes-footer"><span>RigGraph demo · September 2026</span><Link href="/">Explore the marketplace →</Link></footer>
            </article>
        </main>
    );
}