import Link from "next/link";
import { SparkleIcon } from "@/components/Icons";

export default function NotesPage() {
    return (
        <main>
            <header className="site-header compact-header"><Link href="/" className="wordmark" aria-label="Looply home"><span>L</span>LOOPLY</Link><nav className="desktop-nav"><Link href="/">Browse gear</Link><Link href="/builder">Loop Builder</Link><Link href="/notes">Notes</Link></nav><Link className="back-link" href="/">← Back to browse</Link></header>
            <article className="notes-page">
                <p className="eyebrow"><span className="eyebrow-dot" /> CognitioLabs candidate assessment</p>
                <h1>Notes on the demo.</h1>
                <p className="notes-intro">Looply is a responsive, AI-enabled second-hand marketplace demo for Singapore musicians building a first home-recording setup. Its point of view is simple: used music gear is easier to buy when the connection details are visible before the seller chat begins.</p>
                <div className="notes-grid">
                    <section className="note-block"><h2>1. What I built and who it is for</h2><p>A public, mobile-first marketplace where a beginner or intermediate musician can browse structured used listings, inspect an item detail page, search in natural language, and ask questions about a catalogue record. The demo focuses on home-recording essentials: audio interfaces, microphones, monitors, headphones, MIDI controllers, and a handful of required accessories. <Link href="/builder">Loop Builder</Link> turns saved gear into a PC-part-picker-style rig: My Gear hearts feed a draggable cart sidebar, adaptive slots respond to owned equipment and the shopper&apos;s goal, and Loop Check evaluates every change.</p></section>
                    <section className="note-block"><h2>2. What is seeded, simulated, or limited</h2><ul><li>The catalogue contains 18 illustrative listings and fabricated seller identities, condition, price, and Singapore pickup locations.</li><li>Listing photos are illustrative Unsplash images rather than photos supplied by real sellers.</li><li>My Gear and the personal niche-gear library persist in the browser&apos;s local storage only; there are no accounts. Request-to-buy, payment, delivery, messaging, and pickup remain simulated or unavailable.</li><li>Compatibility states are concise, seeded notes—not a complete rules engine or safety certification.</li><li>The demo cannot verify real-time availability, condition, authenticity, driver compatibility, electrical safety, or undocumented accessories. Personal library entries are explicitly unverified.</li></ul></section>
                    <section className="note-block"><h2>3. AI implementation</h2><p>I built the experience with an AI coding assistant. The demo includes four server-side AI integration points: natural-language listing search, listing/catalogue Q&amp;A, Loop Builder slot suggestions, and automatic Loop Check build evaluation. When configured, they call the CognitioLabs OpenRouter gateway using <code>CLASSGW_KEY</code> and <code>CLASSGW_BASE_URL</code> environment variables only. No browser-side API key is required or exposed.</p><ul><li>Looply embeds the seeded listing records and compact connection knowledge base with <code>openai/text-embedding-3-small</code>, then retrieves the closest context for each request.</li><li>Chat uses <code>openai/gpt-4o-mini</code>; search can only return validated existing listing IDs, Q&amp;A must return known facts separately from unknowns, slot suggestions are validated against the catalogue category set, and Loop Check output is validated into a fixed status/issues/suggestions/swaps shape.</li><li>Server responses treat retrieved catalogue text as data rather than instructions. If embedding or chat access fails, deterministic seeded-catalogue fallbacks keep the public demo usable, including a rule-based compatibility engine for phantom power, XLR/USB/monitor/headphone mismatches, and missing accessories.</li><li>Loop Builder drag-and-drop uses native browser APIs with a tap-to-place select fallback so the mobile-first layout stays usable on touch screens.</li><li>Retrieval is hybrid: the in-memory listing + knowledge-base index is merged with up to two Postgres <code>document_chunks</code> rows (pgvector cosine plus full-text search), each carrying a citation label the model is asked to repeat in knownFacts. If the database or gateway is unavailable, the same routes silently skip DB chunks and keep working.</li><li>A registry-gated TypeScript ingestion pipeline (<code>npm run db:ingest</code>) discovers only approved manufacturer sources, checks robots/terms before fetching, preserves raw bytes with SHA-256 versioning, chunks product-aware sections, embeds them, and extracts ports/requirements as <code>pending_review</code> structured facts. Raw files land in gitignored <code>data/raw/</code>.</li><li>Vetted niche-gear entries graduate via <code>npm run db:promote-custom</code>, which requires <code>--approve</code> and a reviewer name and stores them as <code>seller_statement</code> chunks labelled &ldquo;Community library entry — unverified&rdquo;.</li></ul></section>
                    <section className="note-block"><h2>Looply product naming</h2><p>The feature system uses clear, repeatable names: <strong>Loop Builder</strong> for visual setup creation, <strong>My Gear</strong> for saved equipment, <strong>Loop Check</strong> for compatibility results, <strong>My Loop</strong> for a complete setup, <strong>Smart Swap</strong> for alternatives, <strong>Shared Loop</strong> for public setup pages, <strong>Loop Kits</strong> for seller bundles, and <strong>Looply Assist</strong> for the AI guide. This demo surfaces Loop Builder, My Gear, Loop Check, Smart Swap, and Looply Assist; the remaining labels are reserved for the broader product roadmap.</p></section>
                    <section className="note-block"><h2>4. What I chose not to build, and why</h2><p>I prioritised two credible buyer journeys—browse → item detail → grounded search or Q&amp;A, and save → Loop Builder → automatic Loop Check—over full marketplace infrastructure. Authentication, seller onboarding, photo ingestion, moderation, payments, and logistics would dilute the quality of the assessed experience in this time-boxed demo. Server-persisted saved gear is intentionally browser-local instead: it demonstrates the cart-to-builder flow without accounts.</p></section>
                    <section className="note-block"><h2>5. Known issues and unfinished parts</h2><ul><li>Real model responses require the candidate gateway variables to be set on the deployed service. Without them, the same UI works using transparent deterministic catalogue fallbacks.</li><li>Catalogue facts were manually seeded and are representative, not a complete or independently audited product database.</li><li>Natural-language matching is limited by the small demo catalogue and does not yet enforce every physical signal-path rule.</li><li>Images load from Unsplash and therefore depend on external image availability.</li><li>There are no automated tests yet; the intended manual checks are public/incognito browse, mobile layout, search, Q&amp;A, save-to-builder, drag-and-drop plus tap-to-place, and this notes page.</li></ul></section>
                </div>
                <aside className="notes-callout"><SparkleIcon /><p><strong>Safety and transparency note.</strong> Model-backed output is treated as a catalogue explanation, not expert technical advice. The UI labels uncertainty and source limitations rather than claiming that an item is safe, authentic, or guaranteed compatible.</p></aside>
                <footer className="notes-footer"><span>Looply demo · September 2026</span><Link href="/">Explore the marketplace →</Link></footer>
            </article>
        </main>
    );
}